version: '3.1'

services:

        wordpress:
                image: wordpress
                restart: always
                ports:
                        - 8080:80
                environment:
                        WORDPRESS_DB_PASSWORD: example
                volumes:
                        - $HOME/src_wordpress:/var/www/html
        mysql:
                image: mysql:5.7
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: example
                volumes:
                        - $HOME/data_wordpress:/var/lib/mysql
